# Generated by Django 2.0.3 on 2019-11-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191122_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subs',
            old_name='sub_name',
            new_name='name',
        ),
    ]
