# Generated by Django 2.0.3 on 2019-11-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191122_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Pizza_Name',
        ),
    ]
