# Generated by Django 2.0.3 on 2019-12-01 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191124_0228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza_Toppings',
        ),
    ]
