# Generated by Django 2.0.3 on 2019-12-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_delete_pizza_toppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=64, unique=True)),
                ('topping_type', models.CharField(max_length=64)),
            ],
        ),
    ]
