# Generated by Django 2.0.3 on 2019-12-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.CharField(choices=[('1', 'Pepperoni'), ('2', 'Sausage'), ('3', 'Mushroom'), ('4', 'Onions'), ('5', 'Ham'), ('6', 'Canadian Bacon'), ('7', 'Eggplant'), ('8', 'Pineapple'), ('9', 'Tomato & Basil'), ('10', 'Green Pepper'), ('11', 'Hamburger'), ('12', 'Spinach'), ('13', 'Artichoke'), ('14', 'Barbeque Chicken'), ('15', 'Buffalo Chicken'), ('16', 'Anchovies'), ('17', 'Black Olives'), ('18', 'Fresh Garlic'), ('19', 'Zucchini')], max_length=1),
        ),
    ]
