# Generated by Django 2.0.3 on 2019-12-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
    ]
